name: flutter_login_app
description: Projeto Flutter simples com login, navegação e barra de pesquisa.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  shared_preferences:
  sqflite:
  path: 
  cupertino_icons: ^1.0.2
  go_router: ^10.1.2
  http: ^1.4.0
  provider: ^6.1.5

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
